name: CI

on: [push, pull_request]

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Add steps to run your workflow and verify it works
      - name: Run workflow
        run: |
          # your workflow commands here

  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt-get install -y clang-format
      - name: Run clang-format check
        run: |
          git clang-format --diff --quiet